services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        value: 8461610744:AAGhqcrnJBj9nPuCSHx2oE7ZuMezycJ9Uow
